In [1]:
import pandas as pd
import os
import numpy as np

In [2]:
df = pd.read_csv(os.path.join('communities', 'communities.data'), header = None, na_values = '?')

In [3]:
df.columns = ["state"
,"county"
,"community"
,"communityname"
,"fold"
,"population"
,"householdsize"
,"racepctblack"
,"racePctWhite"
,"racePctAsian"
,"racePctHisp"
,"agePct12t21"
,"agePct12t29"
,"agePct16t24"
,"agePct65up"
,"numbUrban"
,"pctUrban"
,"medIncome"
,"pctWWage"
,"pctWFarmSelf"
,"pctWInvInc"
,"pctWSocSec"
,"pctWPubAsst"
,"pctWRetire"
,"medFamInc"
,"perCapInc"
,"whitePerCap"
,"blackPerCap"
,"indianPerCap"
,"AsianPerCap"
,"OtherPerCap"
,"HispPerCap"
,"NumUnderPov"
,"PctPopUnderPov"
,"PctLess9thGrade"
,"PctNotHSGrad"
,"PctBSorMore"
,"PctUnemployed"
,"PctEmploy"
,"PctEmplManu"
,"PctEmplProfServ"
,"PctOccupManu","PctOccupMgmtProf"
,"MalePctDivorce"
,"MalePctNevMarr"
,"FemalePctDiv"
,"TotalPctDiv"
,"PersPerFam"
,"PctFam2Par"
,"PctKids2Par"
,"PctYoungKids2Par"
,"PctTeen2Par"
,"PctWorkMomYoungKids"
,"PctWorkMom"
,"NumIlleg"
,"PctIlleg"
,"NumImmig"
,"PctImmigRecent"
,"PctImmigRec5"
,"PctImmigRec8"
,"PctImmigRec10"
,"PctRecentImmig"
,"PctRecImmig5"
,"PctRecImmig8"
,"PctRecImmig10"
,"PctSpeakEnglOnly"
,"PctNotSpeakEnglWell"
,"PctLargHouseFam"
,"PctLargHouseOccup"
,"PersPerOccupHous"
,"PersPerOwnOccHous"
,"PersPerRentOccHous"
,"PctPersOwnOccup"
,"PctPersDenseHous"
,"PctHousLess3BR"
,"MedNumBR"
,"HousVacant"
,"PctHousOccup"
,"PctHousOwnOcc"
,"PctVacantBoarded"
,"PctVacMore6Mos"
,"MedYrHousBuilt"
,"PctHousNoPhone"
,"PctWOFullPlumb"
,"OwnOccLowQuart"
,"OwnOccMedVal"
,"OwnOccHiQuart"
,"RentLowQ"
,"RentMedian"
,"RentHighQ"
,"MedRent"
,"MedRentPctHousInc"
,"MedOwnCostPctInc"
,"MedOwnCostPctIncNoMtg"
,"NumInShelters"
,"NumStreet"
,"PctForeignBorn"
,"PctBornSameState"
,"PctSameHouse85"
,"PctSameCity85"
,"PctSameState85"
,"LemasSwornFT"
,"LemasSwFTPerPop"
,"LemasSwFTFieldOps"
,"LemasSwFTFieldPerPop"
,"LemasTotalReq"
,"LemasTotReqPerPop"
,"PolicReqPerOffic"
,"PolicPerPop"
,"RacialMatchCommPol"
,"PctPolicWhite"
,"PctPolicBlack"
,"PctPolicHisp"
,"PctPolicAsian"
,"PctPolicMinor"
,"OfficAssgnDrugUnits"
,"NumKindsDrugsSeiz"
,"PolicAveOTWorked"
,"LandArea"
,"PopDens"
,"PctUsePubTrans"
,"PolicCars"
,"PolicOperBudg"
,"LemasPctPolicOnPatr"
,"LemasGangUnitDeploy","LemasPctOfficDrugUn"
,"PolicBudgPerPop"
,"ViolentCrimesPerPop"]

In [4]:
for column in ['racePctWhite', 'racepctblack', 'racePctAsian', 'racePctHisp']:
    qt = df[column].quantile(.5)
    high_idx = np.where(df[column] > qt)[0]
    low_idx = np.where(df[column] <= qt)[0]
    df.loc[high_idx, column] = 1
    df.loc[low_idx, column] = 0

In [5]:
df

,state,county,community,communityname,fold,population,householdsize,racepctblack,racePctWhite,racePctAsian,...,LandArea,PopDens,PctUsePubTrans,PolicCars,PolicOperBudg,LemasPctPolicOnPatr,LemasGangUnitDeploy,LemasPctOfficDrugUn,PolicBudgPerPop,ViolentCrimesPerPop
0,8,NaN,NaN,Lakewoodcity,1,0.19,0.33,0.0,1.0,1.0,...,0.12,0.26,0.20,0.06,0.04,0.90,0.5,0.32,0.14,0.20
1,53,NaN,NaN,Tukwilacity,1,0.00,0.16,1.0,0.0,1.0,...,0.02,0.12,0.45,NaN,NaN,NaN,NaN,0.00,NaN,0.67
2,24,NaN,NaN,Aberdeentown,1,0.00,0.42,1.0,0.0,1.0,...,0.01,0.21,0.02,NaN,NaN,NaN,NaN,0.00,NaN,0.43
3,34,5.0,81440.0,Willingborotownship,1,0.04,0.77,1.0,0.0,1.0,...,0.02,0.39,0.28,NaN,NaN,NaN,NaN,0.00,NaN,0.12
4,42,95.0,6096.0,Bethlehemtownship,1,0.01,0.55,0.0,1.0,1.0,...,0.04,0.09,0.02,NaN,NaN,NaN,NaN,0.00,NaN,0.03
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1989,12,NaN,NaN,TempleTerracecity,10,0.01,0.40,1.0,1.0,1.0,...,0.01,0.28,0.05,NaN,NaN,NaN,NaN,0.00,NaN,0.09
1990,6,NaN,NaN,Seasidecity,10,0.05,0.96,1.0,0.0,1.0,...,0.02,0.37,0.20,NaN,NaN,NaN,NaN,0.00,NaN,0.45
1991,9,9.0,80070.0,Waterburytown,10,0.16,0.37,1.0,0.0,0.0,...,0.08,0.32,0.18,0.08,0.06,0.78,0.0,0.91,0.28,0.23
1992,25,17.0,72600.0,Walthamcity,10,0.08,0.51,0.0,1.0,1.0,...,0.03,0.38,0.33,0.02,0.02,0.79,0.0,0.22,0.18,0.19
1993,6,NaN,NaN,Ontariocity,10,0.20,0.78,1.0,0.0,1.0,...,0.11,0.30,0.05,0.08,0.04,0.73,0.5,1.00,0.13,0.48

In [6]:
high_idx = np.where(df['ViolentCrimesPerPop'] > .7)[0]
low_idx = np.where(df['ViolentCrimesPerPop'] <= .7)[0]

In [7]:
df.loc[high_idx, 'ViolentCrimesPerPop'] = 1
df.loc[low_idx, 'ViolentCrimesPerPop'] = 0

In [8]:
df = df.dropna(axis = 1)

In [9]:
df.to_csv(os.path.join('communities', 'communities_process.csv'))

In [10]:
sum(df['state'] > 20)

1326

In [11]:
sum(df['state'] < 20)

667